# material-theme
# Hexo theme made with Material Design Light (MDL - https://getmdl.io/)
# https://github.com/benTheBike/material-theme

# MDL CSS link
# Choose your preferred color theme from https://getmdl.io/customize/index.html and copy the URL to the hosted CSS below. (Ex. https://code.getmdl.io/1.3.0/material.amber-lime.min.css)
# Or leave blank and provide your own local copy inside of /layout/_partials/head.ejs
mdl_css: https://code.getmdl.io/1.3.0/material.blue_grey-deep_orange.min.css

# Theme color
# Value for <meta name='theme-color'>
theme_color: red

# Favicon path
# Unless using an external URL, path is relative to /source
favicon_path: "https://ben.bike/favicon.png"

# HighlightJS CSS file. Leave blank for default.
# Play around with the styles on https://highlightjs.org/ and pick a highlight_code_theme.min.css on https://cdnjs.com/libraries/highlight.js/
# Links look like https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/$style_name$.min.css
hljs_css: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css

# This theme uses a layout with a header and navigation drawer. 'Header items' are items in the right of the header, and 'Drawer items' are items in the slideout drawer.
# Leave blank if you don't want items in one of them.
# See "Fixed header" on https://getmdl.io/components/index.html#layout-section/layout
# Format:  Displayed Text: Url
#     Ex:  Homepage: http://example.com

# Header items
header_url: /

header_items:
  HeaderItem1: /header_item_1
  HeaderItem2: /header_item_2

# Drawer items
drawer_items:
  DrawerItem1: /drawer_item_1
  DrawerItem2: /drawer_item_2

# Header title
header_title: Header Title

# Drawer title
drawer_title: Drawer Title

# Footer
# Footer Title
footer_title: Footer Title

# Footer items
footer_items:
  FooterItem1: /footer_item_1
  FooterItem2: /footer_item_2

# Links
google_analytics_id: UA-117978515-1
twitter_link:
facebook_link:
google_plus_link: 
